name: Run all tests

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:
    inputs:
      tag:
        description: Pass tests tag to run
        required: true
        default: "@all"

env:
  TEST_USERNAME: ${{ secrets.USER_NAME }}
  TEST_PASSWORD: ${{ secrets.PASSWORD }}
  API_KEY: ${{ secrets.API_KEY }}
  BASE_TEAM_ID: ${{ secrets.BASE_TEAM_ID }}

  TZ: 'Europe/Warsaw'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.45.1-jammy
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run all Cucumber tests
        if: ${{ github.event.inputs.tag == '@all' }}
        run: npm test

      - name: Run Cucumber tests with given tag
        if: ${{ github.event.inputs.tag != '@all' }}
        run: |
          echo "Running tests with tag '${{ github.event.inputs.tag }}'"
          npx cucumber-js --tags "${{ github.event.inputs.tag }}"

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
